#!/usr/bin/env bash
# Configuring HAProxy load balancer

# Update the package list 
sudo apt-get -y update

# Install required packages
sudo apt-get -y install software-properties-common

# Add the HAProxy repository and install HAProxy 2.0
sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

# HAProxy configuration
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers

backend webservers
    balance roundrobin
    server 452935-web-01 34.229.136.14:80 check
    server 452935-web-02 100.25.129.163:80 check
"
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Start the HAProxy service
sudo service haproxy start
