#!/usr/bin/env bash
# Main script logic
# Function to restart the script
# Function to start the script
# Function to stop the script

SCRIPT_NAME="manage_my_process"
PID_FILE="/var/run/my_process.pid"


start() {
  if [ -f "$PID_FILE" ]; then
    echo "$SCRIPT_NAME is already running (PID: $(cat $PID_FILE))"
  else
    nohup ./$SCRIPT_NAME > /dev/null 2>&1 &
    echo $! > $PID_FILE
    echo "$SCRIPT_NAME started"
  fi
}

stop() {
  if [ -f "$PID_FILE" ]; then
    pid=$(cat $PID_FILE)
    kill "$pid"
    rm -f "$PID_FILE"
    echo "$SCRIPT_NAME stopped"
  else
    echo "$SCRIPT_NAME is not running"
  fi
}

restart() {
  stop
  start
  echo "$SCRIPT_NAME restarted"
}


case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

