#!/bin/bash
# This script displays "Best School" 10 times using a while loop
# On the 9th iteration it displays "Hi"
# An if statement must be used

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]; then
        echo -e "Best School\nHi"
    else
        echo "Best School"
    fi

    ((count++))
done
