#!/bin/bash
# This script loops from 1 t 10
# Displays "bad luck" for the 4th loop iteration
# Displays "good luck" for the 8th loop iteration
# Displays "Best School" for the other iterations
# Must use while loop, if, elif and else statements

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    elif [ $count -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi

    ((count++))
done
