#!/bin/bash
# Use a for loop to iterate over non-hidden files in the current directory
# In a list format, without hidden files
# Must use a for loop

for file in *; do
    if [[ $file != .* ]]; then
        name_part=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_part"
    fi
done
